config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: "homes#top"
  resources :filmimage, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/filmimage.rb
class Filmimage < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
end

app/controllers/filmimage_controller.rb
class FilmimageController < ApplicationController
  def new
    @filmimage = Filmimage.new
  end

  def create
    @filmimage = Filmimage.new(filmimage_params)
    @filmimage.user_id = current_user.id
    if @filmimage.save
      redirect_to filmimage_index_path
    else
      @filmimages = Filmimage.all
      @user = current_user
      render :index
    end
  end
  
  def index
    @filmimages = Filmimage.all
    @filmimage = Filmimage.new
    @user = current_user
  end

  def show
    @filmimage = Filmimage.find(params[:id])
    @post_comment = PostComment.new
  end

  def update
    @filmimage = Filmimage.find(params[:id])
    if @filmimage.update(filmimage_params)
      redirect_to filmimage_path(@filmimage.id)
    else
      render :edit
    end
  end

  def destroy
    filmimage = Filmimage.find(params[:id])
    filmimage.destroy
    redirect_to filmimage_index_path
  end

  private

  def filmimage_params
    params.require(:filmimage).permit(:image, :caption)
  end
end

app/helpers/filmimage_helper.rb
module FilmimageHelper
end

app/views/filmimage/index.html.erb
<body>
 <div class='container mt-5'>
  <h3>新着投稿</h3>
   <div class='row'>
    <% @filmimages.each do |f| %>
      <div class='col-md-4'>
       <div class="card" style="width: 18rem;">
        <p><%= image_tag @user.get_profile_image(50,50) %><%= f.user.name %></p>
         <div class="bd-placeholder-img card-img-top h-100">
         </div>
         <div class="card-body">
          <p><%= f.caption %></p>
         </div>
       </div>
      </div>
    <% end %>
    <%= render 'layouts/footer' %>
   </div>
 </div>
</body>

app/views/filmimage/new.html.erb
<div class="container">
  <div class="row no-gutters">
   <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto text-center rounded px-0 my-5">
    <h2 class="text-dark py-4 mb-0">新規投稿</h2>
    <%= form_with model: @filmimage, url: filmimage_index_path, method: :post do |f| %>
      <h4>画像</h4>
      <%= f.file_field :image, accept: "image/*" %>
      <h4>キャプション</h4>
      <%= f.text_area :caption %>
      <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-5" %>
    <% end %>
   </div>
  </div>
</div>

app/views/filmimage/show.html.erb
<div>
  <%= image_tag @filmimage.get_image %>
  <p>キャプション：<%= @filmimage.caption %></p>
  <p><%= image_tag 'sample-author1.jpg' %></p>
  <p>ユーザーネーム：<%= @filmimage.user.name %></p>
  <p>投稿日：<%= @filmimage.created_at.strftime('%Y/%m/%d') %></p>
  <% if @filmimage.user == current_user %>
    <%= link_to "削除", post_image_path(@filmimage), method: :delete %>
  <% end %>
</div>

<div>
  <p>コメント件数：<%= @post_image.post_comments.count %></p>
  <% @post_image.post_comments.each do |post_comment| %>
    <p><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
    <% if post_comment.user == current_user %>
      <%= link_to "削除", filmimage_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
    <% end %>
  <% end %>

<% if @filmimage.favorited_by?(current_user) %>
    <p>
      <%= link_to filmimage_favorites_path(@filmimage), method: :delete do %>
        ♥<%= @filmimage.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to filmimage_favorites_path(@filmimage), method: :post do %>
        ♡<%= @filmimage.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
</div>
<div>
  <%= form_with model: [@post_image, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>