config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: "homes#top"
  resources :filmimage, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :filmimage

end

app/models/filmimage.rb
class Filmimage < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :filmimage, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
   find_or_create_by!(email: 'test@gmail.com') do |user|
    user.password = test1111
    user.password_confirmation = user.password
    user.nickname = 'サンプル'
    user.birthday = '2000-01-01'
   end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    filmimage_index_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    filmimage = Filmimage.find(params[:filmimage_id])
    favorite = current_user.favorites.new(filmimage_id: post_image.id)
    favorite.save
    redirect_to filmimage_path(filmimage)
  end

  def destroy
    filmimage = Filmimage.find(params[:filmimage_id])
    favorite = current_user.favorites.find_by(filmimage_id: post_image.id)
    favorite.destroy
    redirect_to filmimage_path(filmimage)
  end

end

app/controllers/filmimage_controller.rb
class FilmimageController < ApplicationController
  def new
    @filmimage = Filmimage.new
  end

  def create
    @filmimage = Filmimage.new(filmimage_params)
    @filmimage.user_id = current_user.id
    if @filmimage.save
      redirect_to filmimage_index_path
    else
      @filmimages = Filmimage.all
      @user = current_user
      render :index
    end
  end
  
  def index
    @filmimages = Filmimage.all
    @filmimage = Filmimage.new
    @user = current_user
  end

  def show
    @filmimage = Filmimage.find(params[:id])
    @post_comment = PostComment.new
  end

  def update
    @filmimage = Filmimage.find(params[:id])
    if @filmimage.update(filmimage_params)
      redirect_to filmimage_path(@filmimage.id)
    else
      render :edit
    end
  end

  def destroy
    filmimage = Filmimage.find(params[:id])
    filmimage.destroy
    redirect_to filmimage_index_path
  end

  private

  def filmimage_params
    params.require(:filmimage).permit(:image, :caption)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    filmimage = Filmimage.find(params[:filmimage_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.filmimage_id = film_image.id
    comment.save
    redirect_to filmimage_path
  end

  def destroy
    PostComment.find(params[:id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only:[:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    @filmimage = @user.filmimage
    @filmimages = Filmimage.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
     if @user.update(user_params)
       redirect_to user_path(@user.id)
     else
       render :edit
     end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
   @user = User.find(params[:id])
   unless @user == current_user
     redirect_to user_path(current_user)
   end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/filmimage_helper.rb
module FilmimageHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom">
 <div class='container mt-5'>
  <div class='row'>
    <div>
     <%= link_to filmimage_index_path, class: 'nav-link text-dark' do %>
      <i class="fas fa-home"></i>
     <% end %>
    </div>

    <div>
     <%= link_to new_filmimage_path, class: 'nav-link text-dark' do %>
      <i class="fas fa-plus-square"></i>
     <% end %>
    </div>

    <div>
     <%= link_to user_path(current_user.id), class: 'nav-link text-dark' do %>
      <i class="fas fa-user"></i>
     <% end %>
    </div>
  </div>
 </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Filgraph</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--<meta name="viewport" content="width=device-width,initial-scale=1">-->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/19e535bf81.js" crossorigin="anonymous"></script>
  </head>

  <body　class="d-flex flex-column vh-100">
   <header>
    <nav class="navbar navbar-expand-lg navbar-light">
     <div class="container">
      <a class="navbar-brand p-3" href="/"><%= image_tag('phonto.jpg') %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-link text-dark">
            <%= link_to destroy_user_session_path, method: :delete do %>
             <i class="fas fa-sign-out-alt">ログアウト</i>
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
     </div>
    </nav>
   </header>
    <%= yield %>
  </body>

</html>